language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hirokim0114/docker_react_hm -f Dockerfile.dev .

script:
  - docker run -e CI=true hirokim0114/docker_react_hm npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-hm"
  env: "DockerReactHm-env"
  bucket_name: "elasticbeanstalk-us-east-2-319947790842"
  bucket_path: "docker-react-hm"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  #自分のサイトURLイメージ/App名/環境名
  #AWS_ACCESS_KEYとAWS_SECRET_KEYはAWSへアクセスするTravisに環境変数を追加しておく
  #DockerReactHm-env.eba-ms3bvjgi.us-east-2.elasticbeanstalk.com/docker-react-hm/DockerReactHm-env